AWSTemplateFormatVersion: '2010-09-09'
Description: Déploiement d'une app Streamlit sur EC2 avec clé intégrée

Parameters:
  GitRepoURL:
    Type: String
    Default: https://github.com/ton-utilisateur/ton-repo.git
    Description: Lien GitHub application Streamlit

Resources:
  StreamlitSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Autorise HTTP pour Streamlit
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  StreamlitInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: my-key  # Remplace par le nom exact de ta clé EC2 (sans .pem)
      ImageId: ami-0fc5d935ebf8bc3bc  # Ubuntu 22.04 LTS - région Paris
      SecurityGroups:
        - !Ref StreamlitSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          apt install -y python3-pip git
          pip3 install streamlit pandas requests
          cd /home/ubuntu
          git clone ${GitRepoURL}
          cd $(basename ${GitRepoURL} .git)
          nohup streamlit run app.py --server.port 80 --server.enableCORS false &

Outputs:
  AppURL:
    Description: Lien de l'application Streamlit
    Value: !Sub "http://${StreamlitInstance.PublicIp}"
