[supabase]
url = "https://khvzryhkcimncqogvwrj.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtodnpyeWhrY2ltbmNxb2d2d3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDk5MzksImV4cCI6MjA2MjYyNTkzOX0.qakKka_XJZtzuoV05Y-HZYb-tfIpVPynqHWdmk7bvug"